apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: postgrest
          image: postgrest/postgrest:devel
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: PGRST_SERVER_HOST
              value: "0.0.0.0"
            - name: PGRST_SERVER_PORT
              value: "3000"
            - name: PGRST_DB_URI
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PGRST_DB_URI
            - name: PGRST_DB_SCHEMAS
              value: "public"
            - name: PGRST_DB_ANON_ROLE
              value: "admin"