apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "123456"
  POSTGRES_DB: "db_api"

  #postgres://USERNAME:PASSWORD@SERVICE_NAME:PORT/DATABASE_NAME
  PGRST_DB_URI: "postgres://admin:123456@postgres-service:5432/db_api"